# Generated by Django 3.2.16 on 2023-02-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_auto_20230208_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
